export const RESET_SERVER_MESSAGES = "RESET_SERVER_MESSAGES";
export const SERVER_ERROR = "SERVER_ERROR";
export const SERVER_MESSAGE = "SERVER_MESSAGE";

export const USER_FETCH_PROFILE = "USER/FETCH_PROFILE";
export const USER_SET_PROFILE = "USER/SET_PROFILE";
export const USER_SIGNIN = "USER/SIGNIN";
export const USER_SIGNIN_ATTEMPT = "USER/SIGNIN_ATTEMPT";
export const USER_SIGNIN_SESSION = "USER/SIGNIN_SESSION";
export const USER_SIGNOUT = "USER/SIGNOUT";
export const USER_SIGNOUT_SESSION = "USER/SIGNOUT_SESSION";
export const USER_SIGNUP = "USER/SIGNUP";
